sources:
  - glyphs/BalsamiqSans-Roman.glyphs
  #- glyphs/BalsamiqSans-Italic.glyphs
axisOrder:
  - wght
  - ital
familyName: Balsamiq Sans

# Sources aren't VF compatible
buildVariable: false
checkCompatibility: false

# Outlines are quadratic
reverseOutlineDirection: false
removeOutlineOverlaps: false

# Hit the needed code paths to insert the right metadata into the sources before
# they hit the compiler.
interpolate: true
