sources:
  - glyphs/BalsamiqSans-Roman.glyphs
  - glyphs/BalsamiqSans-Italic.glyphs
axisOrder:
  - wght
  - ital
familyName: Balsamiq Sans

# Sources aren't VF compatible
buildVariable: false
checkCompatibility: false

# Outlines are quadratic
reverseOutlineDirection: false
removeOutlineOverlaps: false
